site_name: Luis A. D'Afonseca - Material Didático
site_url: https://material-didatico.github.io

theme:
  name: material
  favicon: img/favicon.png
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home:  index.md
  - CFVVI: cfvv1/index.md
  - IS:    is/index.md
  - LaTeX: latex/index.md
