
site_name: Luis A. D'Afonseca - Material Didático
site_url: https://material-didatico.github.io

nav:
  - Home: index.md
  - Graduação:
    - Cálculo de Funções de Várias Vaiáveis I: pages/cfvv1/index.md
    - Integração e Séries: pages/is/index.md
    - EDPs:                pages/edp/index.md
    - Administração:       pages/administracao/index.md
    - Cálculo IV:          pages/calculo_4/index.md
  - Ensino Básico:
    - Infinito:         pages/infinito/index.md
    - Construção Civil: pages/civil/index.md
    - Métodos Numéricos para o Ensino Médio: pages/met_num_medio/index.md
    - Investimentos:    pages/investimentos/index.md
    - Zip Math:         pages/zip_math/index.md
  - Profmat:
    - Nice Booklet: pages/booklet/index.md
  - Outros:
    - LaTeX:  pages/latex/latex.md
    - Python: pages/python/index.md

theme:
  name: material
  language: pt-BR
  logo: img/favicon.png
  favicon: img/favicon.png
  custom_dir: docs/overrides

  features:
    - navigation.instant

  font:
    text: "Lato"
    code: "Fira Code"

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extras.css
